services:
  app:
    build: .
    container_name: kokany-neptun
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/kokany-neptun
    depends_on:
      - mongo
    networks:
      - neptun-network
    volumes:
      - ./src:/app/src
    command: node src/server.js

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - neptun-network

volumes:
  mongo-data:
    external: true

networks:
  neptun-network:
    driver: bridge